addons:
  sonarcloud:
    organization: dfalessi-github
    token:
      secure: 542889412b44dd26612c5c9752eab11afe92a7e7
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar